default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gyakuten_clone_group30_development

test:
  <<: *default
  database: gyakuten_clone_group30_test

production:
  <<: *default
  database: gyakuten_clone_group30_production
  username: gyakuten_clone_group30
  password: <%= ENV['GYAKUTEN_CLONE_GROUP_DATABASE_PASSWORD'] %>
